### ISSUE TITLE
Please Update to 1.21

### ISSUE THREAD

**Issue by BlackBox-cmd** [kkllffaa/meteor-litematica-printer#32]

**Comment by Kyuunex** [comment]
note: litematica is still on 1.20.6. perhaps update to 1.20.6 first

**Comment by Gamekind135** [comment]
@Kyuunex Please

**Comment by Gamekind135** [comment]
@kkllffaa PLEASE

**Comment by kkllffaa** [comment]
I can update to 1.20.6 tomorrow but i still cant do 1.21 without litematica updating to it first

**Comment by kkllffaa** [comment]
i updated to 1.21, but you need to use fork of litematica https://github.com/sakura-ryoko/litematica and malilib https://github.com/sakura-ryoko/malilib since original author will no longer maitain these mods, more info here: https://old.reddit.com/r/litematica/comments/1di4o3h/announcement_about_litematicas_future_and_updates/

**Comment by kkllffaa** [comment]
no problem, there you go: https://github.com/kkllffaa/meteor-litematica-printer/releases/tag/mc_1.20.6_meteor_0.5.7_ver_1.3

**Comment by Kyuunex** [comment]
Thank you!
